<a href="https://colab.research.google.com/github/Aman05gupta/Vector/blob/main/Vector.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1. Definition and Basic Properties
A vector is an ordered collection of numbers (called components or elements) which can be represented as a point in space.

**Notation:**

A vector can be denoted as **v** and written in various forms:


*   Column vector
*   Row vector
*   Reshaping Vectors
*   Transposing Vectors

In [1]:
import numpy as np

In [5]:
column_vector = np.array([[1],[2],[3]])

row_vector = np.array([1,2,3])

print("Column Vector:\n",column_vector)

print("Row Vector:\n",row_vector)

Column Vector:
 [[1]
 [2]
 [3]]
Row Vector:
 [1 2 3]


## Reshaping Vectors
If you have a one-dimensional array and you want to explicitly convert it to a column or row vector, you can use the reshape method.

In [7]:
# One-dimensional array
vector = np.array([1,2,3,])

In [10]:
# Convert to column vector
column_vector = vector.reshape(-1,1)
print("Column Vector:\n", column_vector)

Column Vector:
 [[1]
 [2]
 [3]]


In [11]:
# Convert to row vector

row_vector = vector.reshape(1,-1)
print("Row Vector:\n",row_vector)

Row Vector:
 [[1 2 3]]


### Transposing Vectors
You can transpose a row vector to get a column vector and vice versa using the T attribute.

In [18]:
# Transposing a row vector to get a column vector
row_vector = np.array([[1,2,3]])
column_vector_form_row = row_vector.T
print("Column Vector form Row Vector:\n",column_vector_form_row)

Column Vector form Row Vector:
 [[1]
 [2]
 [3]]


In [19]:
# Transposing a column vector to get a row vector
column_vector = np.array([[1],[2],[3]])
row_vector_form_column = column_vector.T
print("Row Vector form Column Vector:\n", row_vector_form_column)

Row Vector form Column Vector:
 [[1 2 3]]


# 2. Types of Vectors
**Zero Vector :** A zero vector is a vector where all components are zero.

**Unit Vector :** A unit vector is a vector with a magnitude of 1.  

**Basis Vectors :** Basis vectors are standard unit vectors along the axes of a coordinate system. In 3D space.



In [20]:
# Creating a zero vector of size 3 (example for 3-dimensional space)
zero_vector = np.zeros(3)
print("Zero Vector\n", zero_vector)

Zero Vector
 [0. 0. 0.]


In [22]:
# Creating a unit vector along the x-axis in 3D space
unit_vector_x = np.array([1,0,0])
print("Unit Vector\n", unit_vector_x)

Unit Vector
 [1 0 0]


In [26]:
# Creating basis vectors in 3D space
e1 = np.array([1,0,0])
e2 = np.array([0,1,0])
e3 = np.array([0,0,1])

print(e1)
print(e2)
print(e3)

[1 0 0]
[0 1 0]
[0 0 1]


In [23]:
# Creating basis vectors in 3D space
basis_vectors = np.array([[1,0,0],[0,1,0],[0,0,1]])
print("Basis Vecrtor:\n",basis_vectors)


Basis Vecrtor:
 [[1 0 0]
 [0 1 0]
 [0 0 1]]


In [29]:
# Creating basis Vectors in 2D Sapace
b1 = np.array([1,0])
b2 = np.array([0,1])

print("Basis Vectors in 2D Space:\n", b1,b2)

Basis Vectors in 2D Space:
 [1 0] [0 1]


In [30]:
print(b1)
print(b2)

[1 0]
[0 1]


# Geometric Vectors
**Position Vector**
A position vector specifies the position of a point relative to a reference point or origin.

**Displacement Vector**
A displacement vector represents the change in position from one point to another.



In [31]:
# Position vector in 3D space

position_vector = np.array([2, 3, 5])
print("Position Vector:", position_vector)


Position Vector: [2 3 5]


In [32]:
# Displacement vector from point A to point B

point_A = np.array([1, 2, 3])
point_B = np.array([4, 5, 6])

displacement_vector = point_B - point_A
print("Displacement Vector:", displacement_vector)


Displacement Vector: [3 3 3]


# Algebraic Vectors
**Row Vector**
A row vector is represented horizontally and is useful in matrix operations.

**Column Vector**
A column vector is represented vertically and is essential in linear transformations and solving systems of equations.

In [33]:
# Row vector
row_vector = np.array([[1, 2, 3]])
print("Row Vector:", row_vector)


Row Vector: [[1 2 3]]


In [34]:
# Column vector
column_vector = np.array([[1], [2], [3]])
print("Column Vector:\n", column_vector)


Column Vector:
 [[1]
 [2]
 [3]]


# Free Vectors
A free vector can move freely in space without changing its magnitude or direction.

In [35]:
# Free vector example

vector1 = np.array([3, 4])
vector2 = np.array([-1, 2])

print("Vector 1:", vector1)
print("Vector 2:", vector2)


Vector 1: [3 4]
Vector 2: [-1  2]


# Bound Vectors

A bound vector is associated with a specific point or origin in space.

In [36]:
# Bound vector example

origin = np.array([0, 0])
endpoint = np.array([3, 4])

bound_vector = endpoint - origin
print("Bound Vector:", bound_vector)


Bound Vector: [3 4]


# Position Vectors

**Position Vector** (again, for clarity)
Position vectors are used to define the position of a point relative to a reference point or origin.

In [37]:
# Another example of a position vector

position_vector2 = np.array([-1, 2, 5])
print("Position Vector 2:", position_vector2)


Position Vector 2: [-1  2  5]


# Vector Operations

*   Vector Addition
*   Vector Subtraction
*   Scalar Multiplication
*   Dot Product (Inner Product)
*   Cross Product (only applicable in 3D)
*   Vector Magnitude (Norm)
*   Vector Projection
*   Calculating Orthogonality and Angle Between Vectors












In [38]:

# Define two vectors
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

# Vector addition
vector_sum = vector1 + vector2
print("Vector Sum:", vector_sum)


Vector Sum: [5 7 9]


In [39]:
# Vector subtraction
vector_diff = vector2 - vector1
print("Vector Difference:", vector_diff)


Vector Difference: [3 3 3]


In [40]:
# Scalar multiplication
scalar = 2
scaled_vector = scalar * vector1
print("Scaled Vector:", scaled_vector)


Scaled Vector: [2 4 6]


In [41]:
# Dot product
dot_product = np.dot(vector1, vector2)
print("Dot Product:", dot_product)


Dot Product: 32


In [42]:
# Define two 3D vectors
vector3 = np.array([1, 0, 0])
vector4 = np.array([0, 1, 0])

# Cross product
cross_product = np.cross(vector3, vector4)
print("Cross Product:", cross_product)


Cross Product: [0 0 1]


In [43]:
# Vector magnitude (norm)
magnitude_vector1 = np.linalg.norm(vector1)
print("Magnitude of Vector 1:", magnitude_vector1)


Magnitude of Vector 1: 3.7416573867739413


In [44]:
# Define two vectors
vector_a = np.array([3, 4])
vector_b = np.array([1, 1])

# Vector projection of vector_a onto vector_b
proj_vector_a_on_b = np.dot(vector_a, vector_b) / np.linalg.norm(vector_b) * vector_b
print("Vector Projection of vector_a onto vector_b:", proj_vector_a_on_b)


Vector Projection of vector_a onto vector_b: [4.94974747 4.94974747]


In [45]:

# Define two vectors
v = np.array([1, 0, 0])
w = np.array([0, 1, 0])

# Calculate dot product
dot_product = np.dot(v, w)

# Check orthogonality
if dot_product == 0:
    print("Vectors v and w are orthogonal.")
else:
    print("Vectors v and w are not orthogonal.")

# Calculate angle between vectors
magnitude_v = np.linalg.norm(v)
magnitude_w = np.linalg.norm(w)
cos_theta = dot_product / (magnitude_v * magnitude_w)
angle_degrees = np.arccos(cos_theta) * 180 / np.pi

print("Angle between vectors v and w (degrees):", angle_degrees)


Vectors v and w are orthogonal.
Angle between vectors v and w (degrees): 90.0
